# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatbot_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chatbot_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63hatbot_service.proto\x12\x0e\x63hatbotservice\"\x1f\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\" \n\x0eInferenceReply\x12\x0e\n\x06result\x18\x01 \x01(\t2i\n\x12HuggingFaceService\x12S\n\x10GenerateResponse\x12\x1d.chatbotservice.PromptRequest\x1a\x1e.chatbotservice.InferenceReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROMPTREQUEST']._serialized_start=41
  _globals['_PROMPTREQUEST']._serialized_end=72
  _globals['_INFERENCEREPLY']._serialized_start=74
  _globals['_INFERENCEREPLY']._serialized_end=106
  _globals['_HUGGINGFACESERVICE']._serialized_start=108
  _globals['_HUGGINGFACESERVICE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
